Dennis zack temp branch2
WSU-4110/Able pull request #57
Opened 2019-12-03 21:03 UTC by DennisZack

2019-12-03 21:07 UTC, laurel-walker approved these changes
approved

2019-12-03 21:27 UTC, laurel-walker requested changes
format as flask

2019-12-03 21:27 UTC, laurel-walker commented on app/forms.py
> +from sqlalchemy import create_engine
delete

2019-12-03 21:27 UTC, laurel-walker commented on app/routes.py
> +    # avg = avg/reviews.count()
uncomment

2019-12-03 21:27 UTC, laurel-walker commented on app/routes.py
>      return render_template('main.html')
remove

2019-12-03 21:27 UTC, laurel-walker commented on app/routes.py
> +    return render_template('User Profile.html', reviews=all_reviews)
rename route and use conditional to eliminate redundancy

2019-12-03 21:27 UTC, laurel-walker commented on app/routes.py
> +    return render_template('User Profile.html')
remove

2019-12-03 21:27 UTC, laurel-walker commented on app/templates/User Profile.html
> +<!DOCTYPE html>
delete and extends base.html

2019-12-03 21:27 UTC, laurel-walker commented on app/templates/User Profile.html
> +</html>
format like flask app

2019-12-05 06:10 UTC, laurel-walker requested changes

2019-12-05 06:10 UTC, laurel-walker commented on app/static/css/style.css
> +
delete from this line down

2019-12-05 06:10 UTC, laurel-walker commented on app/static/css/user_page.css
> +
css does not need to extend base

2019-12-05 17:15 UTC, laurel-walker approved these changes
approved

2019-12-05 18:17 UTC, KenGajefski requested changes
You need to unversion able.db. You should not be tracking the database in the GitHub repository.

Does your CSS use anything from BootStrap? Can you create a wiki page with how the page looks?

2019-12-05 18:17 UTC, KenGajefski commented on app/forms.py
> +import smtplib
This does not need to be here. It is not used in this file at all.

2019-12-05 18:17 UTC, KenGajefski commented on app/routes.py
> +            print('Email sent!')  # Let the user know that their email was sent sussessfully
Printing here will do nothing for the user view. Can be removed.

2019-12-05 18:17 UTC, KenGajefski commented on app/routes.py
>      return render_template('main.html')
This does not need to be a route. This can be made a method in a file and imported then ran in the appropriate route where the button will be.

2019-12-05 18:17 UTC, KenGajefski commented on app/templates/base.html
> +                <li><a href="user_profile">User Profile</a></li>
This needs to be enclosed in the Jinja templating style as the links/routes below it.

2019-12-06 02:55 UTC, KenGajefski reviewed
Approved.

2019-12-06 02:56 UTC, merged